import type { UJLTColorSet } from '@ujl-framework/types';
import type { GeneratedPalette } from './palettes.js';

/**
 * Converts a GeneratedPalette to a UJLTColorSet.
 *
 * This function maps the palette structure (generated by `generateColorPalette`) into
 * the UJL theme token format used by the theme system.
 *
 * Mapping strategy:
 * - Light/dark variants: Directly mapped from palette.light, palette.dark, etc.
 * - Shades 50-400: Fall back to `palette.light.oklch` if missing (lighter shades)
 * - Shade 500: Uses `palette.baseOklch` (the input color) if missing
 * - Shades 600-950: Fall back to `palette.dark.oklch` if missing (darker shades)
 *
 * This fallback strategy ensures a consistent gradient even if some shades are missing,
 * maintaining visual harmony in the theme.
 *
 * @param palette - The generated palette from `generateColorPalette` or related functions
 * @returns A UJLTColorSet ready for use in UJL theme tokens
 *
 * @example
 * ```ts
 * const palette = generateColorPalette("#3b82f6");
 * const colorSet = mapGeneratedPaletteToColorSet(palette);
 * // Result: { light, lightForeground, lightText, dark, darkForeground, darkText, shades: {...} }
 * ```
 */
export function mapGeneratedPaletteToColorSet(palette: GeneratedPalette): UJLTColorSet {
	return {
		light: palette.light.oklch,
		lightForeground: palette.lightFg.oklch,
		lightText: palette.lightText.oklch,
		dark: palette.dark.oklch,
		darkForeground: palette.darkFg.oklch,
		darkText: palette.darkText.oklch,
		shades: {
			50: palette.shades[50]?.oklch ?? palette.light.oklch,
			100: palette.shades[100]?.oklch ?? palette.light.oklch,
			200: palette.shades[200]?.oklch ?? palette.light.oklch,
			300: palette.shades[300]?.oklch ?? palette.light.oklch,
			400: palette.shades[400]?.oklch ?? palette.light.oklch,
			500: palette.shades[500]?.oklch ?? palette.baseOklch,
			600: palette.shades[600]?.oklch ?? palette.dark.oklch,
			700: palette.shades[700]?.oklch ?? palette.dark.oklch,
			800: palette.shades[800]?.oklch ?? palette.dark.oklch,
			900: palette.shades[900]?.oklch ?? palette.dark.oklch,
			950: palette.shades[950]?.oklch ?? palette.dark.oklch
		}
	};
}
