name: Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Let us know what's missing, unclear, or incorrect.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - "Missing documentation"
        - "Unclear/confusing content"
        - "Incorrect information"
        - "Broken link"
        - "Typo or grammar"
        - "Code example not working"
        - "Other"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Link to the affected documentation page
      placeholder: "https://ujl-framework.org/guide/..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What's Wrong?
      description: Describe the issue with the current documentation
      placeholder: |
        What is missing, unclear, or incorrect?
        What did you expect to find?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: |
        What should be added, changed, or clarified?
        Feel free to provide text suggestions or outline the structure.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: Screenshots, related documentation, external references, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
